<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/MasterPage.Master" CodeBehind="DepartmentGridView.aspx.cs" Inherits="CircularManagementSystem.DepartmentGridView" %>
<asp:Content ID="contentHeader" runat="server" ContentPlaceHolderID="contentMaster">
    <div>
        <asp:HyperLink ID="LinkViewEmployee" runat="server" NavigateUrl="~/EmployeeGridView.aspx" Text="ViewEmployees" align="right"></asp:HyperLink>
        <asp:GridView ID="DepartmentView" runat="server" AutoGenerateColumns="False" DataKeyNames="Department_id" AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" ShowFooter="True" OnRowCancelingEdit="DepartmentView_RowCancelingEdit"
            OnRowDeleting="DepartmentView_RowDeleting" OnRowEditing="DepartmentView_RowEditing" OnRowUpdating="DepartmentView_RowUpdating">
            <Columns>
                <asp:TemplateField HeaderText="DepartmentId" runat="server">
                    <ItemTemplate>
                        <asp:Label ID="labelId" runat="server" Text='<%# Bind("Department_id") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:LinkButton ID ="btnInsert" Text ="Insert" runat ="server" OnClick ="LbInsert_Click" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="DepartmentName" runat="server">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtName" runat="server" Text='<%# Bind("DepartmentName") %>'></asp:TextBox>
                    </EditItemTemplate>
                     <ItemTemplate>
                        <asp:Label ID="labelName" runat="server" Text='<%# Bind("DepartmentName") %>'></asp:Label>
                    </ItemTemplate>
                     <FooterTemplate>
                        <asp:TextBox ID="txtDepartmentNameFooter" runat="server" />
                         <asp:RegularExpressionValidator ID="NameValid" ValidationExpression="^[a-zA-Z'.\s]{1,50}" runat="server" ErrorMessage="Enter valid department name" ControlToValidate="txtDepartmentNameFooter" ForeColor="Red"></asp:RegularExpressionValidator>
                        <asp:RequiredFieldValidator ID="NameFieldValidator" runat="server" ControlToValidate="txtDepartmentNameFooter"
                 ForeColor="Red" Display = "Dynamic" ErrorMessage = "Required" />
                    </FooterTemplate>
                </asp:TemplateField>
                    </Columns>
        </asp:GridView>
    </div>
</asp:Content>