<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/MasterPage.Master" CodeBehind="GridView.aspx.cs" Inherits="CircularManagementSystem.WebForm1" %>

<asp:Content ID="contentHeader" runat="server" ContentPlaceHolderID="contentLogin" runtat="server">
    <div>
        <asp:GridView ID="employeeView" runat="server" AutoGenerateColumns="False" DataKeyNames="employeeId" AutoGenerateDeleteButton="True"
           AutoGenerateEditButton="True" OnRowCancelingEdit="EmployeeView_RowCancelingEdit"
            OnRowDeleting="EmployeeView_RowDeleting" OnRowEditing="EmployeeView_RowEditing" OnRowUpdating="EmployeeView_RowUpdating">
            <Columns>
                <asp:TemplateField HeaderText="EmployeeId" runat="server">
                    <ItemTemplate>
                        <asp:Label ID="labelId" runat="server" Text='<%# Bind("EmployeeId") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="EmployeeName" runat="server">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtName" runat="server" Text='<%# Bind("EmployeeName") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="labelName" runat="server" Text='<%# Bind("EmployeeName") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="EmployeePhone" runat="server">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtPhone" runat="server" Text='<%# Bind("EmployeePhoneNumber") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="labelPhone" runat="server" Text='<%# Bind("EmployeePhoneNumber") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
    </div>

</asp:Content>
